---
title: "Demo Dashboard"
author: "rmarkdown.rstudio.com"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    
---

```{r setup, include=FALSE}
library(plotly)
library(plyr)
library(flexdashboard)
library(tidyr)
library(DT)
library(forecast)
library(dplyr)
library(ggplot2)
library(tidyr)


#LOADING DATASET
df = read.csv("F:/Demand Forecasting Thesis/Seasonality/Daily_Report_2020.csv")

#Changing the date format to POSTXLT format
df$Date = strptime(x=df$Date,
                   format = "%m/%d/%Y")

#Changing the POSTXlt format to date format and date type
df$Date = as.Date(df$Date)

#PICKING THE SPECIFIC VARIABLES
df = df %>% select(Date,
                   Jackets)

#Changing the name of the columns
colnames(df)[2]="y"

#Loading the forecasts
sarimax = read.csv("F:/Demand Forecasting Thesis/Ensemble/sarimax.csv")
prophet = read.csv("F:/Demand Forecasting Thesis/Ensemble/prophet.csv")
neural = read.csv("F:/Demand Forecasting Thesis/Ensemble/neural.csv")

#Create a test data
test = df %>% filter(Date >= "2020-12-01")

#Ensemble DataFrame
ensemble = cbind(test, sarimax, prophet)

#Ensemble FOrecast
ensemble = transform(ensemble, 
                     ensemble_forecast = rowMeans(ensemble[,3:ncol(ensemble)]))


```

ENSEMBLE
=======================================================================

Row
-----------------------------------------------------------------------

### GGPLOT

```{r}
p <- ggplot(df, aes(x=Date, y=y))+
  geom_line()+
  xlab("Time")+
  ylab("Adult Jackets")+
  theme(text = element_text(size=20))+
  scale_x_date(date_labels = "%Y %b")    

ggplotly(p)
```



### Forecast

```{r}
pivoted_ensemble <- ensemble %>% 
  pivot_longer(-c(Date),
               names_to = "forecast",
               values_to = "value")
ggplot_plot <- ggplot(pivoted_ensemble, aes(x=Date, y= value)) +
  geom_line(aes(color=forecast), size=1) +
  theme_minimal()
interactive_plot <- ggplotly(ggplot_plot)
interactive_plot

```

Row
-----------------------------------------------------------------------

### ACCURACY

```{r}
accuracy_metrics <- accuracy(ensemble$ensemble_forecast, ensemble$y)
accuracy_table <- as.data.frame(accuracy_metrics)
accuracy_table

```

### ACCURACY

```{r}

```

DATA SET UTILIZED
=======================================================================

Row
-----------------------------------------------------------------------

### DATA SET

```{r}
datatable(df)

```

### TEST SET

```{r}
datatable(test)

```

Row
-----------------------------------------------------------------------

### 

```{r}


```

### 

```{r}

```
