---
title: "Demo Dashboard"
author: "rmarkdown.rstudio.com"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(forecast)
library(plotly)
library(DT)

#load the dataset
df = read.csv("F:/Demand Forecasting Thesis/Seasonality/Daily_Report_2020.csv")

#Transform the Date Variable
df$Date = strptime(x = df$Date,
                   format = "%m/%d/%Y")
df$Date = as.Date(df$Date)

#Pick the variables
df = df %>% select(Date,
                   Adults.Jackets,
                   Easter,
                   Thanksgiving,
                   Christmas,
                   Temperature)

#Change variable name
colnames(df)[2] = "y"


#Training and test set
training = df %>% filter(Date < '2020-12-01')
test = df %>% filter(Date >= '2020-12-01')

#Transform the time series
#7 for daily, 52 for weekly, 12 for monthly, 4 for quarterly
#5 for weekdays
training_y = ts(training$y, frequency = 7)

#Extract the regressors
training_reg = as.matrix(training[, 3:ncol(training)])
test_reg = as.matrix(test[, 3:ncol(test)])

#Model
model = nnetar(y = training_y,
               p = 1,
               P = 1, 
               size = 3,
               xreg = training_reg,
               decay = 0.1)

#Predictions
predictions = forecast(model, xreg = test_reg)


```

SARIMAX
=======================================================================

Row
-----------------------------------------------------------------------

### BUBBLE PLOT

```{r}
#Create bubble plot
p <- ggplot(df, aes(x = Date, y = y)) +
  geom_line() +
  xlab("Time") +
  ylab("Adult Jackets Demand") +
  theme(text = element_text(size = 20)) +
  scale_x_date(date_labels = "%Y %b")
ggplotly(p)

p <- ggplot(df, aes(x = Date, y = y)) +
  geom_line() +
  xlab("Time") +
  ylab("Jacket Demand") +
  theme(text = element_text(size = 20)) +
  scale_x_date(date_labels = "%Y %b")
ggplotly(p)
```



### 

```{r}


```

Row
-----------------------------------------------------------------------

### FORECAST

```{r}
#Plotting
plot_neural <- autoplot(predictions)
ggplotly(plot_neural)

```

### ACCURACY

```{r}
accuracy_metrics <- accuracy(predictions$mean, test$y)
accuracy_table <- as.data.frame(accuracy_metrics)
accuracy_table
```

DATA SET UTILIZED
=======================================================================

Row
-----------------------------------------------------------------------

### DATA SET

```{r}
datatable(df)

```

### TRAINING SET

```{r}
datatable(training)

```

Row
-----------------------------------------------------------------------

### TEST SET

```{r}
datatable(test)

```

### 

```{r}

```
